import { Navbar } from "@/components"
import "./globals.css"
import type { Metadata } from "next"
import DynamicBG from "../components/DynamicBG"

export const metadata: Metadata = {
  title: {
    template: "%s | OW2 Skin Randomiser",
    default: "OW2 Skin Randomiser",
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <DynamicBG>
            <Navbar />
            {children}
          </DynamicBG>
        </div>
      </body>
    </html>
  )
}
