"use client"

import { Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: {
    template: '%s | OW2 Skin Randomiser',
    default: 'OW2 Skin Randomiser',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = usePathname();
  let bgBackground = ''

  switch (router) {
    case '/ashe':
      bgBackground = 'bg-ashe'
      break;
    case '/dva':
      bgBackground = 'bg-dva'
      break;
    case '/reaper':
      bgBackground = 'bg-reaper'
      break;
    case '/sigma':
      bgBackground = 'bg-sigma'
      break;
    case '/soldier_76':
      bgBackground = 'bg-soldier76'
      break;
    case '/zenyatta':
      bgBackground = 'bg-zenyatta'
      break;
    default:
      bgBackground = 'bg-home'
      break; 
  }

  return (
    <html lang="en">
      <body className={`${bgBackground} bg-cover`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
