import React from "react"
import { Soldier76_Skins } from "@/constants"
import Image from "next/image"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Soldier 76",
  description: "Generated by create next app",
}

const Soldier76 = () => {
  const randomSoldierSkin =
    Soldier76_Skins[Math.floor(Math.random() * Soldier76_Skins.length)]

  return (
    <div className="flex h-screen flex-col items-center">
      <h1 className="bold p-4 text-3xl">Soldier 76</h1>
      <div className="grid p-4 sm:grid-cols-1 md:grid-cols-2">
        <div className="relative flex flex-col sm:h-[250px] sm:w-[250px] md:h-[450px] md:w-[450px]">
          <Image
            src={randomSoldierSkin.image}
            alt={randomSoldierSkin.name}
            width="0"
            height="0"
            sizes="100vw"
            className="h-auto w-full"
          />
        </div>
        <div className="bg-opacity-6 m-2 flex flex-col bg-slate-600 p-12">
          <div className="grid grid-cols-2">
            <h3 className="sm:text-md md:text-2xl">Name</h3>
            <h3 className="sm:text-md md:text-2xl">{randomSoldierSkin.name}</h3>
          </div>
          <div className="grid grid-cols-2">
            <h3 className="sm:text-md md:text-2xl">Rating</h3>
            <h3 className="sm:text-md md:text-2xl">
              {randomSoldierSkin.rating}
            </h3>
          </div>
          <div className="grid grid-cols-2">
            <h3 className="sm:text-md md:text-2xl">Coins</h3>
            <h3 className="sm:text-md md:text-2xl">
              {randomSoldierSkin.coins}
            </h3>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Soldier76
