import React from "react"
import { Ashe_Skins } from "@/constants"
import Image from "next/image"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Ashe",
  description: "Generated by create next app",
}

const Ashe = () => {
  const randomAsheSkin =
    Ashe_Skins[Math.floor(Math.random() * Ashe_Skins.length)]

  return (
    <div className="flex min-h-screen flex-col items-center">
      <h1 className="bold p-4 text-3xl">Ashe</h1>
      <div className="grid p-4 sm:grid-cols-1 md:grid-cols-2">
        <div className="relative flex flex-col sm:h-[250px] sm:w-[250px] md:h-[450px] md:w-[450px]">
          <Image
            src={randomAsheSkin.image}
            alt={randomAsheSkin.name}
            width="0"
            height="0"
            sizes="100vw"
            className="h-auto w-full"
          />
        </div>
        <div className="bg-opacity-6 m-2 flex flex-col bg-slate-600 p-12">
          <div className="grid grid-cols-2">
            <h3 className="text-2xl">Name</h3>
            <h3>{randomAsheSkin.name}</h3>
          </div>
          <div className="grid grid-cols-2">
            <h3 className="text-2xl">Rating</h3>
            <h3>{randomAsheSkin.rating}</h3>
          </div>
          <div className="grid grid-cols-2">
            <h3 className="text-2xl">Coins</h3>
            <h3>{randomAsheSkin.coins}</h3>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Ashe
